# Commands to export environmental variables for db connections
# Required by read_db.py
export AWS_USER=YourMasterDatabaseName
export AWS_PWD=YourMasterDatabasePassword
export AWS_ACCESS_KEY=YourAccessKey
export AWS_SECRET_KEY=YourSecretKey
export AWS_HOST=YourDatabaseHost
export AWS_PORT=5432
export AWS_DB_NAME=YourDatabaseName (found in RDS dashboard -- default may be 'ebdb')

# Command to export environmental variable for Django project
# Required by read_data.py
export DJANGO_SETTINGS_MODULE=Microcontrollers.settings

# Django secret key
export DJANGO_SECRET_KEY="Copy from e-mail"
